---
- name: Set timezone
  ansible.builtin.timezone:
    name: Etc/UTC

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - git
      - curl
      - htop
      - ufw
      - python3-pip
    state: present
